name: .NET Core
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    types: [opened, synchronize, reopened,closed]
  issues:
        types: [assigned]
  issue_comment:
        types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: LocalizationEditor
      run: dotnet restore
    - name: Build
      working-directory: LocalizationEditor
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: LocalizationEditor
      run: dotnet test --no-restore --verbosity normal
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            branchName: '${issue.number}-${issue.title}'
            autoCloseIssue: true
            branches:
              - label: enhancement
                prefix: feature/
              - label: bug
                prefix: bugfix/
